# Generated by Django 3.1.5 on 2021-01-28 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_image', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('project_description', models.TextField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigned_folder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_foler_project', to='crm.active', verbose_name='Active Folder')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('assigned_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_project', to='projects.project', verbose_name='Project')),
            ],
        ),
    ]
